var json_Hospitales_Tulcan_10 = {
"type": "FeatureCollection",
"name": "Hospitales_Tulcan_10",
"crs": { "type": "name", "properties": { "name": "urn:ogc:def:crs:OGC:1.3:CRS84" } },
"features": [
{ "type": "Feature", "properties": { "full_id": "n941918439", "osm_id": "941918439", "osm_type": "node", "amenity": "hospital", "name": "Clínica CESMED", "emergency": null, "name_en": null, "name_es": null, "addr_city": null, "addr_house": null, "addr_postc": null, "addr_stree": null, "healthcare": null, "healthca_1": null, "opening_ho": null, "operator": null, "payment_ca": null, "phone": null }, "geometry": { "type": "Point", "coordinates": [ -77.7133199, 0.8222852 ] } },
{ "type": "Feature", "properties": { "full_id": "n2190588069", "osm_id": "2190588069", "osm_type": "node", "amenity": "hospital", "name": "Novaclinica del Norte", "emergency": "yes", "name_en": null, "name_es": null, "addr_city": null, "addr_house": null, "addr_postc": null, "addr_stree": null, "healthcare": null, "healthca_1": null, "opening_ho": null, "operator": null, "payment_ca": null, "phone": null }, "geometry": { "type": "Point", "coordinates": [ -77.7289504, 0.8028607 ] } },
{ "type": "Feature", "properties": { "full_id": "n2377999260", "osm_id": "2377999260", "osm_type": "node", "amenity": "hospital", "name": "Hospital General Provincial Luis G. Dávila", "emergency": "yes", "name_en": null, "name_es": null, "addr_city": null, "addr_house": null, "addr_postc": null, "addr_stree": null, "healthcare": null, "healthca_1": null, "opening_ho": null, "operator": null, "payment_ca": null, "phone": null }, "geometry": { "type": "Point", "coordinates": [ -77.710049, 0.830812 ] } },
{ "type": "Feature", "properties": { "full_id": "n4978386021", "osm_id": "4978386021", "osm_type": "node", "amenity": "hospital", "name": "Centro de Salud Sur", "emergency": null, "name_en": "Center of salud Sur", "name_es": "Centro de salud Sur", "addr_city": null, "addr_house": null, "addr_postc": null, "addr_stree": null, "healthcare": null, "healthca_1": null, "opening_ho": null, "operator": null, "payment_ca": null, "phone": null }, "geometry": { "type": "Point", "coordinates": [ -77.7273205, 0.8012926 ] } },
{ "type": "Feature", "properties": { "full_id": "n5408201636", "osm_id": "5408201636", "osm_type": "node", "amenity": "hospital", "name": "Consultorio Médico de Pediatría y Adolescencia", "emergency": "yes", "name_en": null, "name_es": null, "addr_city": "Tulcán", "addr_house": "52-045", "addr_postc": "040103", "addr_stree": "Olmedo y Ayacucho", "healthcare": "hospital", "healthca_1": "paediatrics", "opening_ho": "09:00-19:00", "operator": "CONSULTORIO MÉDICO DE PEDIATRÍA Y ADOLESCENCIA.", "payment_ca": "yes", "phone": "+593062984601" }, "geometry": { "type": "Point", "coordinates": [ -77.7163261, 0.8121806 ] } },
{ "type": "Feature", "properties": { "full_id": "n7545342421", "osm_id": "7545342421", "osm_type": "node", "amenity": "hospital", "name": "Saving lives", "emergency": "yes", "name_en": null, "name_es": null, "addr_city": "Tulcán", "addr_house": null, "addr_postc": null, "addr_stree": "Sumaco y Cayambe", "healthcare": "hospital", "healthca_1": "emergency", "opening_ho": null, "operator": null, "payment_ca": null, "phone": "+593993441368" }, "geometry": { "type": "Point", "coordinates": [ -77.7322046, 0.8053232 ] } }
]
}
